export const BASE_URL = "https://2cea152915e6.ngrok-free.app";
export const API_BASE_URL = `${BASE_URL}/api`;

export const CACHE_TIME_SECONDS = 30 * 1000; // 30 seconds

export const permissions_list = [
    'superuser',
    'order:create',
    'order:view',
    'order:update',
    'order:delete',
    'order:delegate',
    'user:create',
    'user:view',
    'user:update',
    'user:delete',
    'user:password:reset',
    'profile:update',
    'password:update',
    'role:create',
    'role:view',
    'role:update',
    'role:delete',
    'permission:view',
    'status:create',
    'status:view',
    'status:update',
    'status:delete',
    'priority:create',
    'priority:view',
    'priority:update',
    'priority:delete',
    'department:create',
    'department:view',
    'department:update',
    'department:delete',
    'otdel:create',
    'otdel:view',
    'otdel:update',
    'otdel:delete',
    'branch:create',
    'branch:view',
    'branch:update',
    'branch:delete',
    'office:create',
    'office:view',
    'office:update',
    'office:delete',
    'equipment:create',
    'equipment:view',
    'equipment:update',
    'equipment:delete',
    'equipment_type:create',
    'equipment_type:view',
    'equipment_type:update',
    'equipment_type:delete',
];

export const admin_roles = [
    "admin",
    "administrator",
    "superuser",
    "super admin",
    "super-admin",
    "админ",
    "администратор",
    "суперадмин",
    "супер админ",
    "супер-админ",
    "суперадминистратор",
    "супер администратор",
];

export const executor_roles = [
    "user",
    "executor",
    "исполнитель",
    "пользователь",
    "руководитель"
];
