export const BASE_URL = "https://6cbea72d26ee.ngrok-free.app";
export const API_BASE_URL = `${BASE_URL}/api`;

export const CACHE_TIME_SECONDS = 30 * 1000; // 30 seconds

export const permissions_list = [
    'superuser',
    'orders:create',
    'orders:view',
    'orders:update',
    'orders:delete',
    'orders:delegate',
    'users:create',
    'users:view',
    'users:update',
    'users:delete',
    'users:password:reset',
    'profile:update',
    'password:update',
    'roles:create',
    'roles:view',
    'roles:update',
    'roles:delete',
    'permissions:view',
    'statuses:create',
    'statuses:view',
    'statuses:update',
    'statuses:delete',
    'priorities:create',
    'priorities:view',
    'priorities:update',
    'priorities:delete',
    'departments:create',
    'departments:view',
    'departments:update',
    'departments:delete',
    'otdels:create',
    'otdels:view',
    'otdels:update',
    'otdels:delete',
    'branches:create',
    'branches:view',
    'branches:update',
    'branches:delete',
    'offices:create',
    'offices:view',
    'offices:update',
    'offices:delete',
    'equipments:create',
    'equipments:view',
    'equipments:update',
    'equipments:delete',
    'equipment_types:create',
    'equipment_types:view',
    'equipment_types:update',
    'equipment_types:delete',
];
